### ISSUE TITLE
Base64 understanding 

### ISSUE THREAD

**Issue by HabibRh26** [rishitsaiya/CTFlearn-Writeups#65]
Hello, I was trying to follow your writeup, but in this [link](https://github.com/rishitsaiya/CTFlearn-Writeups/tree/master/Forensics/GandalfTheWise) 
<br>
why didnt you input the '+' sign at the beginning when you used the base64 decoder 
<br> and 
<br>
why do I need to view it in hexadecimal to decode the text, Can you please also explain what RFC means?
<br>
--- I am beginner, thanks for the writeup

**Comment by rishitsaiya** [comment]
Hey @HabibRh26 ,

Sorry for this late reply! You can check reference for RFC [here](https://github.com/rishitsaiya/CTFlearn-Writeups/tree/master/Forensics/GandalfTheWise).

Thanks to @vivian-dai for adding the reference.
