### ISSUE TITLE
nonfunctional link

### ISSUE THREAD

**Issue by vivian-dai** [rishitsaiya/CTFlearn-Writeups#84]
in [Favorite Color](https://github.com/rishitsaiya/CTFlearn-Writeups/tree/master/Binary/Favorite%20Color) the link to [https://www.embeddedhacker.com/2020/01/hacking-walkthrough-ctflearn-binary-medium/](https://www.embeddedhacker.com/2020/01/hacking-walkthrough-ctflearn-binary-medium/) doesn't work

also wondering if you're welcome to contributions

**Comment by rishitsaiya** [comment]
Sorry bro for the non-functional link! Well many other writeups available now!

Also I am very much open to contributions 👍 (just please follow the same format of `README.md` I have done so far in all challenges)
